[build]
  command = "npm run build -w client"
  publish = "client/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/src/**"]

# Redirect SPA routes to index.html
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

# Proxy API to Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
